###
POST http://localhost:3000/tenants
content-type: application/json

{
    "name": "Acme Corp"
}

###
POST http://localhost:3000/departments
Content-Type: application/json

{
    "name": "IT Department",
    "tenantId": "{{$dotenv DEFAULT_TENANT_ID}}",
    "sortOrder": 1
}

###
POST http://localhost:3000/attendants
content-type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "tenantId": "{{$dotenv DEFAULT_TENANT_ID}}",
    "departmentId": "{{$dotenv DEFAULT_DEPARTMENT_ID}}"
}


###
GET http://localhost:3000/attendants

###
GET http://localhost:3000/conversations

###
POST http://localhost:3000/conversations/{{$dotenv CONVERSATION_ID}}/messages
Content-Type: application/json

{
    "attendantId": "{{$dotenv ATTENDANT_ID}}",
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}

###
PATCH http://localhost:3000/conversations/{{$dotenv CONVERSATION_ID}}/close